/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const MatchPerformance = IDL.Record({
  'playerId' : IDL.Nat,
  'runs' : IDL.Nat,
  'wickets' : IDL.Nat,
});
export const Match = IDL.Record({
  'id' : IDL.Nat,
  'team1' : IDL.Nat,
  'team2' : IDL.Nat,
  'date' : Time,
  'performances' : IDL.Vec(MatchPerformance),
});
export const CategoryType = IDL.Variant({
  'spinBowling' : IDL.Null,
  'bowling' : IDL.Null,
  'allRounder' : IDL.Null,
  'batting' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'dob' : IDL.Text,
  'totalWickets' : IDL.Nat,
  'name' : IDL.Text,
  'localResidence' : IDL.Text,
  'totalRuns' : IDL.Nat,
  'category' : CategoryType,
  'photo' : ExternalBlob,
  'place' : IDL.Text,
  'teamId' : IDL.Nat,
});
export const Team = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMatch' : IDL.Func([IDL.Nat, IDL.Nat, Time], [IDL.Nat], []),
  'deletePlayer' : IDL.Func([IDL.Nat], [], []),
  'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'getBestAllRounder' : IDL.Func([], [Player], ['query']),
  'getBestBatsman' : IDL.Func([], [Player], ['query']),
  'getBestBowler' : IDL.Func([], [Player], ['query']),
  'getBestSpinBowler' : IDL.Func([], [Player], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatchDetails' : IDL.Func([IDL.Nat], [Match], ['query']),
  'getPlayersByCategory' : IDL.Func(
      [CategoryType],
      [IDL.Vec(Player)],
      ['query'],
    ),
  'getPlayersByTeam' : IDL.Func([IDL.Nat], [IDL.Vec(Player)], ['query']),
  'getTeamById' : IDL.Func([IDL.Nat], [IDL.Opt(Team)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPlayerPerformance' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'registerPlayer' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        CategoryType,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePlayer' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        CategoryType,
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const MatchPerformance = IDL.Record({
    'playerId' : IDL.Nat,
    'runs' : IDL.Nat,
    'wickets' : IDL.Nat,
  });
  const Match = IDL.Record({
    'id' : IDL.Nat,
    'team1' : IDL.Nat,
    'team2' : IDL.Nat,
    'date' : Time,
    'performances' : IDL.Vec(MatchPerformance),
  });
  const CategoryType = IDL.Variant({
    'spinBowling' : IDL.Null,
    'bowling' : IDL.Null,
    'allRounder' : IDL.Null,
    'batting' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'dob' : IDL.Text,
    'totalWickets' : IDL.Nat,
    'name' : IDL.Text,
    'localResidence' : IDL.Text,
    'totalRuns' : IDL.Nat,
    'category' : CategoryType,
    'photo' : ExternalBlob,
    'place' : IDL.Text,
    'teamId' : IDL.Nat,
  });
  const Team = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMatch' : IDL.Func([IDL.Nat, IDL.Nat, Time], [IDL.Nat], []),
    'deletePlayer' : IDL.Func([IDL.Nat], [], []),
    'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getBestAllRounder' : IDL.Func([], [Player], ['query']),
    'getBestBatsman' : IDL.Func([], [Player], ['query']),
    'getBestBowler' : IDL.Func([], [Player], ['query']),
    'getBestSpinBowler' : IDL.Func([], [Player], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatchDetails' : IDL.Func([IDL.Nat], [Match], ['query']),
    'getPlayersByCategory' : IDL.Func(
        [CategoryType],
        [IDL.Vec(Player)],
        ['query'],
      ),
    'getPlayersByTeam' : IDL.Func([IDL.Nat], [IDL.Vec(Player)], ['query']),
    'getTeamById' : IDL.Func([IDL.Nat], [IDL.Opt(Team)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPlayerPerformance' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'registerPlayer' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          CategoryType,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePlayer' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          CategoryType,
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };