/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CategoryType = { 'spinBowling' : null } |
  { 'bowling' : null } |
  { 'allRounder' : null } |
  { 'batting' : null };
export type ExternalBlob = Uint8Array;
export interface Match {
  'id' : bigint,
  'team1' : bigint,
  'team2' : bigint,
  'date' : Time,
  'performances' : Array<MatchPerformance>,
}
export interface MatchPerformance {
  'playerId' : bigint,
  'runs' : bigint,
  'wickets' : bigint,
}
export interface Player {
  'id' : bigint,
  'dob' : string,
  'totalWickets' : bigint,
  'name' : string,
  'localResidence' : string,
  'totalRuns' : bigint,
  'category' : CategoryType,
  'photo' : ExternalBlob,
  'place' : string,
  'teamId' : bigint,
}
export interface Team { 'id' : bigint, 'name' : string }
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMatch' : ActorMethod<[bigint, bigint, Time], bigint>,
  'deletePlayer' : ActorMethod<[bigint], undefined>,
  'getAllMatches' : ActorMethod<[], Array<Match>>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getAllTeams' : ActorMethod<[], Array<Team>>,
  'getBestAllRounder' : ActorMethod<[], Player>,
  'getBestBatsman' : ActorMethod<[], Player>,
  'getBestBowler' : ActorMethod<[], Player>,
  'getBestSpinBowler' : ActorMethod<[], Player>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatchDetails' : ActorMethod<[bigint], Match>,
  'getPlayersByCategory' : ActorMethod<[CategoryType], Array<Player>>,
  'getPlayersByTeam' : ActorMethod<[bigint], Array<Player>>,
  'getTeamById' : ActorMethod<[bigint], [] | [Team]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordPlayerPerformance' : ActorMethod<
    [bigint, bigint, bigint, bigint],
    undefined
  >,
  'registerPlayer' : ActorMethod<
    [string, string, string, string, ExternalBlob, CategoryType, bigint],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePlayer' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      ExternalBlob,
      CategoryType,
      bigint,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];